In [5]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\deepa\OneDrive\Desktop\kidney_disease.csv")
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [7]:
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [8]:
df.tail()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [9]:
df.describe

<bound method NDFrame.describe of       id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent
..   ...   ...   ...    ...  ...  ...     ...       ...         ...
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no

    classification
0              ckd
1              ckd
2              ckd
3              ckd
4              ckd
..             ...
395         notckd
396         notckd
397         notckd
398         notckd
399         notckd

[400 rows x 26 columns]>

In [10]:
df.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [11]:
df.isna().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [12]:
cols = ['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane',]
for col in cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [13]:
df.isna().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [14]:
df.drop_duplicates(inplace = True)

In [15]:
X = df.drop('classification', axis=1)
y = df['classification']

In [16]:
X

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,0,48.0,80.0,1.020,1.0,0.0,normal,normal,notpresent,notpresent,...,15.4,44,7800,5.2,yes,yes,no,good,no,no
1,1,7.0,50.0,1.020,4.0,0.0,normal,normal,notpresent,notpresent,...,11.3,38,6000,5.2,no,no,no,good,no,no
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,9.6,31,7500,5.2,no,yes,no,poor,no,yes
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,11.2,32,6700,3.9,yes,no,no,poor,yes,yes
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,11.6,35,7300,4.6,no,no,no,good,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,15.7,47,6700,4.9,no,no,no,good,no,no
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,16.5,54,7800,6.2,no,no,no,good,no,no
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,15.8,49,6600,5.4,no,no,no,good,no,no
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,14.2,51,7200,5.9,no,no,no,good,no,no
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,15.8,53,6800,6.1,no,no,no,good,no,no

In [17]:
y

0         ckd
1         ckd
2         ckd
3         ckd
4         ckd
        ...
395    notckd
396    notckd
397    notckd
398    notckd
399    notckd
Name: classification, Length: 400, dtype: object

In [48]:
from sklearn.preprocessing import LabelEncoder
encoders = {}

cat_cols = X.select_dtypes(include="object").columns

for col in cat_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))
    encoders[col] = le

# Encode target column
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y.astype(str))

In [49]:
num_cols = df.select_dtypes(include=['int64','float64']).columns.drop('su')
cat_cols=df.select_dtypes(include=['object']).columns
print("Numerical Columns:", num_cols)
print("Categorical Columns:", cat_cols)

Numerical Columns: Index(['id', 'age', 'bp', 'sg', 'al', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo'], dtype='object')
Categorical Columns: Index(['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [75]:
from sklearn.preprocessing import StandardScaler

num_cols = X.select_dtypes(include=['int64', 'float64']).columns

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

In [101]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=15)

X_selected = selector.fit_transform(X, y)

selected_features = X.columns[selector.get_support()]

print(selected_features)
X = X[selected_features]
print(X)

Index(['id', 'sg', 'al', 'pc', 'sod', 'hemo', 'pcv', 'rc', 'htn', 'dm',
       'appet', 'pe'],
      dtype='object')
           id        sg        al        pc       sod      hemo       pcv  \
0   -1.727726  0.421486  0.076249  0.484322 -0.213878  0.899398  0.575394
1   -1.719066  0.421486  2.363728  0.484322 -0.213878 -0.545559 -0.147993
2   -1.710406 -1.421074  0.838742  0.484322 -0.213878 -1.144688 -0.991944
3   -1.701745 -2.342354  2.363728 -2.064742 -2.807977 -0.580802 -0.871379
4   -1.693085 -1.421074  0.838742  0.484322 -0.213878 -0.439831 -0.509686
..        ...       ...       ...       ...       ...       ...       ...
395  1.693085  0.421486 -0.686244  0.484322  1.407434  1.005126  0.937087
396  1.701745  1.342766 -0.686244  0.484322  0.434647  1.287069  1.781038
397  1.710406  0.421486 -0.686244  0.484322  0.002297  1.040369  1.178216
398  1.719066  1.342766 -0.686244  0.484322 -0.213878  0.476483  1.419345
399  1.727726  1.342766 -0.686244  0.484322  0.434647  1.040369  1.660474

           rc       htn        dm     appet        pe
0    0.424844  1.311903  1.209416 -0.507801 -0.484322
1    0.424844 -0.762252 -0.518321 -0.507801 -0.484322
2    0.424844 -0.762252  1.209416  1.969276 -0.484322
3   -1.153525  1.311903 -0.518321  1.969276  2.064742
4   -0.311728 -0.762252 -0.518321 -0.507801 -0.484322
..        ...       ...       ...       ...       ...
395  0.003946 -0.762252 -0.518321 -0.507801 -0.484322
396  1.477091 -0.762252 -0.518321 -0.507801 -0.484322
397  0.635294 -0.762252 -0.518321 -0.507801 -0.484322
398  1.161417 -0.762252 -0.518321 -0.507801 -0.484322
399  1.371866 -0.762252 -0.518321 -0.507801 -0.484322

[400 rows x 12 columns]

In [77]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [78]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [79]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))])

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [81]:
pipe_lr = Pipeline([
    ("model", LogisticRegression(max_iter=1000))
])

In [82]:
pipe_lr.fit(X_train,y_train)

Pipeline(steps=[('model', LogisticRegression(max_iter=1000))])

In [83]:
pipe_dt = Pipeline([
    ("model", DecisionTreeClassifier(random_state=42))
])

In [84]:
pipe_dt.fit(X_train,y_train)

Pipeline(steps=[('model', DecisionTreeClassifier(random_state=42))])

In [85]:
pipe_rf = Pipeline([
    ("model", RandomForestClassifier(random_state=42))
])

In [86]:
pipe_rf.fit(X_train,y_train)

Pipeline(steps=[('model', RandomForestClassifier(random_state=42))])

In [87]:
pipe_knn = Pipeline([
    ("model", KNeighborsClassifier())
])

In [88]:
pipe_knn.fit(X_train,y_train)

Pipeline(steps=[('model', KNeighborsClassifier())])

In [89]:
pipe_svm = Pipeline([
    ("model", SVC())
])

In [90]:
pipe_svm.fit(X_train,y_train)

Pipeline(steps=[('model', SVC())])

In [91]:
pipelines={
     pipe_lr,
     pipe_rf,
     pipe_dt,
     pipe_knn
}

In [92]:
for pip in pipelines:
     pip.fit(X_train,y_train)

In [93]:
lr_pred = pipe_lr.predict(X_test)
dt_pred = pipe_dt.predict(X_test)
rf_pred = pipe_rf.predict(X_test)
knn_pred = pipe_knn.predict(X_test)

In [94]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [96]:
from sklearn.metrics import classification_report

print("Logistic Regression")
print("Accuracy :", accuracy_score(y_test, lr_pred))
print(classification_report(y_test, lr_pred))

Logistic Regression
Accuracy : 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        52
           2       1.00      1.00      1.00        28

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [ ]:
from sklearn.metrics import classification_report

print("Decision Tree")
print("Accuracy :", accuracy_score(y_test, dt_pred))
print(classification_report(y_test, dt_pred))

Decision Tree
Accuracy : 0.9875
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        52
           1       0.00      0.00      0.00         0
           2       1.00      1.00      1.00        28

    accuracy                           0.99        80
   macro avg       0.67      0.66      0.66        80
weighted avg       1.00      0.99      0.99        80

In [98]:
from sklearn.metrics import classification_report

print("Random forest")
print("Accuracy :", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

Random forest
Accuracy : 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        52
           2       1.00      1.00      1.00        28

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [99]:
from sklearn.metrics import classification_report

print("KNN")
print("Accuracy :", accuracy_score(y_test, knn_pred))
print(classification_report(y_test, knn_pred))

KNN
Accuracy : 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        52
           2       1.00      1.00      1.00        28

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [100]:
import joblib
joblib.dump( pipe_rf,"Chronic Kidney Disease.pkl")

['Chronic Kidney Disease.pkl']